const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmt=n=>{if(!isFinite(n))return'∞';let a=Math.abs(n);if(a<1000)return(Math.round(n*10)/10).toString();let u=['K','M','B','T','Qa','Qi'],i=-1;while(Math.abs(n)>=1000&&i<u.length-1){n/=1000;i++}return(Math.round(n*100)/100)+u[i]};
function newState(){return{version:4,era:0,day:1,seconds:0,population:3,popProgress:0,happiness:72,territory:1,prestige:0,legacy:+localStorage.getItem('ember_legacy_v4')||0,resources:{food:40,wood:12,stone:0,knowledge:0,tools:0,metal:0,coin:0,coal:0,steel:0,electricity:0,oil:0,data:0,automation:0,energy:0,alloy:0,antimatter:0},jobs:{food:1,wood:1},buildings:{},tech:{},branches:{},timeline:{},highestPopulation:3,totalKnowledge:0,eventTimer:55,lastSave:Date.now()}}
function load(){try{let d=JSON.parse(localStorage.getItem('ember_civilization_v4'));if(!d)return newState();let b=newState();return{...b,...d,resources:{...b.resources,...(d.resources||{})},jobs:{...b.jobs,...(d.jobs||{})},buildings:d.buildings||{},tech:d.tech||{},branches:d.branches||{},timeline:d.timeline||{},legacy:+localStorage.getItem('ember_legacy_v4')||d.legacy||0}}catch(e){return newState()}}
let G=load();
function assigned(){return Object.values(G.jobs).reduce((a,b)=>a+b,0)}function idle(){return Math.max(0,Math.floor(G.population)-assigned())}
function branchEffects(){let out={global:1,food:1,wood:1,stone:1,knowledge:1,tools:1,metal:1,coin:1,coal:1,steel:1,electricity:1,oil:1,data:1,automation:1,energy:1,alloy:1,antimatter:1,pop:1,consume:1,prestige:1,explore:1,territory:1,build:1,industry:1,happy:0};for(let group of Object.values(BRANCHES)){let id=G.branches[group.title]||G.branches[group.title.replace('路线','')];let c=group.choices.find(x=>x.id===id);if(!c)continue;for(let[k,v]of Object.entries(c.effect||{})){if(k==='happy')out.happy+=v;else out[k]=(out[k]||1)*v}}return out}
function techMults(){let m={global:1,food:1,stone:1,knowledge:1,tools:1,industry:1,data:1,automation:1,energy:1,alloy:1,antimatter:1,pop:1,consume:1,explore:1};if(G.tech.fire)m.consume*=.92;if(G.tech.language)m.knowledge*=1.15;if(G.tech.domestication){m.food*=1.15;m.pop*=1.1}if(G.tech.irrigationTech)m.food*=1.2;if(G.tech.writing)m.knowledge*=1.3;if(G.tech.iron){m.tools*=1.25;m.stone*=1.25}if(G.tech.roads)m.global*=1.08;if(G.tech.printing)m.knowledge*=1.4;if(G.tech.steam)m.industry*=1.45;if(G.tech.electricityTech)m.global*=1.15;if(G.tech.combustion){m.explore*=.85;m.industry*=1.2}if(G.tech.computing){m.knowledge*=1.6;m.data*=1.4}if(G.tech.internet){m.knowledge*=1.25;m.data*=1.25}if(G.tech.roboticsTech){m.automation*=1.7;m.industry*=1.35}if(G.tech.fusionTech)m.energy*=1.8;if(G.tech.spaceflight){m.alloy*=1.7;m.antimatter*=1.7}if(G.tech.antimatterTech)m.antimatter*=2.2;return m}
function bcount(id){return G.buildings[id]||0}
function buildingMults(){let m={global:1,food:1,stone:1,knowledge:1,tools:1,coin:1,industry:1,electricity:1,data:1,automation:1,energy:1,alloy:1,antimatter:1,consume:1};m.consume*=Math.pow(.95,bcount('campfire'));m.food*=Math.pow(1.06,bcount('granary'));m.stone*=Math.pow(1.12,bcount('quarry'));m.tools*=Math.pow(1.18,bcount('workshop'));m.coin*=Math.pow(1.15,bcount('market'));m.knowledge*=Math.pow(1.16,bcount('library'))*Math.pow(1.22,bcount('lab'));m.global*=Math.pow(1.03,bcount('road'))*Math.pow(1.05,bcount('robotics'));m.food*=Math.pow(1.12,bcount('mill'));m.tools*=Math.pow(1.12,bcount('mill'));m.industry*=Math.pow(1.22,bcount('factory'));m.electricity*=Math.pow(1.2,bcount('power'));m.data*=Math.pow(1.25,bcount('datacenter'));m.automation*=Math.pow(1.3,bcount('robotics'));m.energy*=Math.pow(1.3,bcount('fusion'));m.alloy*=Math.pow(1.35,bcount('orbitalYard'));m.antimatter*=Math.pow(1.35,bcount('orbitalYard'));return m}
function popCap(){return 5+bcount('hut')*4+bcount('granary')*2+G.era*3+Math.floor(G.territory*1.5)}
function eraScale(){return Math.pow(1.82,G.era)}
function jobOutput(jobId){let j=JOBS[jobId],n=G.jobs[jobId]||0;if(!n)return 0;let base=j.base*n*eraScale()*(1+G.legacy*.05);let t=techMults(),b=buildingMults(),br=branchEffects();let r=j.res;if(r==='prestige'||r==='build'||r==='industry'||r==='govern')return base*(1+G.era*.08)*br.global*t.global*b.global;let mult=(br[r]||1)*(t[r]||1)*(b[r]||1)*br.global*t.global*b.global;if(['tools','metal','coal','steel','electricity','oil','automation','energy','alloy','antimatter'].includes(r))mult*=br.industry*t.industry*b.industry;return base*mult}
function rates(){let r={};for(let k of Object.keys(RES_NAMES))r[k]=0;for(let id of Object.keys(JOBS)){if((G.jobs[id]||0)<=0)continue;let j=JOBS[id],v=jobOutput(id);if(j.res==='prestige')continue;if(j.res==='build'||j.res==='govern'||j.res==='industry')continue;r[j.res]+=v}
if(G.era>=3)r.metal+=(G.jobs.miner||0)*.12*eraScale();if(G.era>=6){r.coal+=(G.jobs.miner||0)*.1*eraScale();r.steel+=(G.jobs.artisan||0)*.08*eraScale()}if(G.era>=7){r.electricity+=(G.jobs.engineer||0)*.16*eraScale()+bcount('power')*.8*eraScale();r.oil+=(G.jobs.miner||0)*.05*eraScale()}if(G.era>=8)r.data+=(G.jobs.scholar||0)*.14*eraScale()+bcount('datacenter')*.6*eraScale();if(G.era>=9){r.automation+=(G.jobs.engineer||0)*.09*eraScale()+bcount('robotics')*.4*eraScale();r.energy+=bcount('fusion')*.5*eraScale()}if(G.era>=10){r.alloy+=(G.jobs.artisan||0)*.05*eraScale()+bcount('orbitalYard')*.25*eraScale();r.antimatter+=(G.jobs.scholar||0)*.015*eraScale()+bcount('orbitalYard')*.05*eraScale()}
let br=branchEffects(),t=techMults(),b=buildingMults();for(let k in r){r[k]*=(br[k]||1)*(t[k]||1)*(b[k]||1);if(['tools','metal','coal','steel','electricity','oil','automation','energy','alloy','antimatter'].includes(k))r[k]*=br.industry*t.industry*b.industry;r[k]*=br.global*t.global*b.global}
let consumption=G.population*(.36+G.era*.035)*br.consume*t.consume*b.consume;r.food-=consumption;return r}
function growthStatus(){if(G.population>=popCap())return['住房已满',0];let f=G.resources.food/Math.max(1,G.population);if(f<4)return['食物不足',0];if(G.happiness<35)return['幸福度过低',0];let br=branchEffects(),t=techMults();let speed=.024*Math.pow(1.08,G.era)*(br.pop||1)*(t.pop||1)*(0.65+G.happiness/100);return['增长中',speed]}
function exploreCost(){let e=branchEffects(),t=techMults();let c=(30*Math.pow(1.17,G.territory))*e.explore*t.explore;return{food:Math.ceil(c*1.2),wood:Math.ceil(c),coin:G.era>=3?Math.ceil(c*.6):0}}
function canAfford(c){return Object.entries(c).every(([k,v])=>!v||(G.resources[k]||0)>=v)}function pay(c){for(let[k,v]of Object.entries(c))if(v)G.resources[k]-=v}function costText(c){return Object.entries(c).filter(([,v])=>v>0).map(([k,v])=>`${RES_NAMES[k]||k} ${fmt(v)}`).join(' / ')}
function manualGather(k){let gain=(k==='food'?3:2)*(1+G.era*.5)*(1+G.legacy*.05);G.resources[k]+=gain;toast(`${RES_NAMES[k]} +${fmt(gain)}`);render()}window.manualGather=manualGather;
function exploreTerritory(){let c=exploreCost();if(!canAfford(c)){toast('探索资源不足');return}pay(c);let gain=Math.max(1,Math.floor(branchEffects().territory||1));G.territory+=gain;G.prestige+=2+G.era;log(`探索队带回地图：领土 +${gain}。`,'good');render()}window.exploreTerritory=exploreTerritory;
function assignJob(id,d){let cur=G.jobs[id]||0;if(d>0&&idle()<=0)return;G.jobs[id]=Math.max(0,cur+d);render()}window.assignJob=assignJob;
function buildingCost(b){let n=bcount(b.id),c={};for(let[k,v]of Object.entries(b.cost))c[k]=Math.ceil(v*Math.pow(1.2,n));return c}
function build(id){let b=BUILDINGS.find(x=>x.id===id);if(!b||G.era<b.era)return;let n=bcount(id),c=buildingCost(b);if(n>=b.max||!canAfford(c)){toast('资源不足');return}pay(c);G.buildings[id]=n+1;log(`建成「${b.name}」×${n+1}。`,'good');render()}window.build=build;
function research(id){let t=TECHS.find(x=>x.id===id);if(!t||G.tech[id]||G.era<t.era||!canAfford(t.cost)){toast('研究条件不足');return}pay(t.cost);G.tech[id]=1;log(`掌握科技「${t.name}」。`,'event');render()}window.research=research;
function chooseBranch(groupTitle,id){let group=Object.values(BRANCHES).find(g=>g.title===groupTitle),c=group?.choices.find(x=>x.id===id);if(!group||!c||G.era<c.era)return;let old=group.choices.find(x=>x.id===G.branches[groupTitle]);if(old&&c.era<=old.era){toast('只能升级到更晚时代的路线');return}G.branches[groupTitle]=id;log(`发展路线${old?'升级':'确定'}：${group.title} → ${c.name}。`,'event');render()}window.chooseBranch=chooseBranch;
function eraProgress(){let g=ERAS[G.era]?.goal;if(!g)return 1;return clamp((G.population/g.pop)*.34+(G.totalKnowledge/g.knowledge)*.33+(G.territory/g.territory)*.33,0,1)}
function canAdvance(){return G.era<ERAS.length-1&&eraProgress()>=.999}
function advanceEra(){if(!canAdvance()){toast('时代突破条件还没满足');return}G.era++;G.prestige+=10*G.era;G.happiness=Math.min(100,G.happiness+4);log(`时代突破：文明进入「${ERAS[G.era].name}」。`,'event');render()}window.advanceEra=advanceEra;
function restartRun(){if(!confirm('确定重开本局吗？\n会清空本局人口、资源、建筑、科技与分支，但祖灵印记保留。'))return;let legacy=G.legacy;G=newState();G.legacy=legacy;save();$('#log').innerHTML='';log('旧聚落化为灰烬，新的三个人重新围到火边。','event');render()}window.restartRun=restartRun;
function prestigeRun(){if(G.era<10){toast('抵达星际文明后才能进行大传承');return}let gain=Math.max(1,Math.floor(Math.sqrt(G.highestPopulation/100)+Math.sqrt(G.totalKnowledge/10000)+G.territory/12+G.prestige/200));if(!confirm(`让本次文明成为传说？\n获得 ${gain} 个祖灵印记并从头开始。`))return;let next=G.legacy+gain;localStorage.setItem('ember_legacy_v4',next);G=newState();G.legacy=next;save();$('#log').innerHTML='';log(`新的文明继承了 ${next} 个祖灵印记。`,'event');render()}window.prestigeRun=prestigeRun;
function log(t,cl=''){let d=document.createElement('div');d.className=cl;d.textContent=`[第 ${Math.floor(G.day)} 日] ${t}`;$('#log').appendChild(d);while($('#log').children.length>100)$('#log').firstChild.remove();$('#log').scrollTop=999999}
function toast(t){let e=$('#toast');e.textContent=t;e.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);background:#111820;border:1px solid #4a5660;padding:8px 11px;border-radius:6px;font-size:11px;z-index:20';clearTimeout(toast.t);toast.t=setTimeout(()=>e.removeAttribute('style'),1200)}
function eventTick(){let q=Math.random();if(q<.25){let n=Math.ceil(10*eraScale());G.resources.food+=n;log(`丰收季额外获得 ${fmt(n)} 食物。`,'good')}else if(q<.45){let n=Math.ceil(5*eraScale());G.resources.knowledge+=n;G.totalKnowledge+=n;log(`一次意外发现带来 ${fmt(n)} 知识。`,'event')}else if(q<.62){G.happiness=Math.min(100,G.happiness+4);log('节庆让人们暂时忘记劳作，幸福度上升。','good')}else if(q<.8){let loss=Math.ceil(G.resources.food*.05);G.resources.food=Math.max(0,G.resources.food-loss);log(`储藏事故损失 ${fmt(loss)} 食物。`,'bad')}else{G.prestige+=5+G.era*2;log('远方聚落开始传颂你的文明。','event')}}
function tick(dt){let r=rates();let admin=jobOutput('administrator'),builder=jobOutput('builder'),soldier=jobOutput('soldier');let civic=1+Math.log1p(admin+builder)*.035;for(let k in r)r[k]*=civic;G.prestige+=Math.log1p(soldier)*.018*dt*branchEffects().prestige;for(let k in r){G.resources[k]=Math.max(0,(G.resources[k]||0)+r[k]*dt);if(k==='knowledge'&&r[k]>0)G.totalKnowledge+=r[k]*dt}let [status,speed]=growthStatus();if(speed>0){G.popProgress+=speed*dt;if(G.popProgress>=1){let add=Math.floor(G.popProgress);G.popProgress-=add;G.population=Math.min(popCap(),G.population+add);G.highestPopulation=Math.max(G.highestPopulation,G.population);log(`${add} 名新成员加入文明。`,'good')}}let target=68+branchEffects().happy;if(G.resources.food/G.population>15)target+=7;if(G.resources.food/G.population<3)target-=25;target=clamp(target,15,100);G.happiness+=(target-G.happiness)*.02*dt;G.seconds+=dt;G.day=1+G.seconds/20;G.eventTimer-=dt;if(G.eventTimer<=0){eventTick();G.eventTimer=55+Math.random()*55}checkTimeline()}
function checkTimeline(){for(let m of TIMELINE)if(!G.timeline[m.id]&&m.test(G)){G.timeline[m.id]=1;G.prestige+=3;log(`文明纪事：${m.text}`,'event')}}
function visibleResources(){return Object.keys(RES_NAMES).filter(k=>RESOURCE_UNLOCK[k]<=G.era||G.resources[k]>0)}
function render(){let r=rates(),[gs,spd]=growthStatus();$('#population').textContent=fmt(G.population);$('#popCap').textContent=fmt(popCap());$('#idle').textContent=idle();$('#happiness').textContent=Math.round(G.happiness);$('#territory').textContent=fmt(G.territory);$('#prestige').textContent=fmt(G.prestige);$('#eraName').textContent=`${ERAS[G.era].name} · ${ERAS[G.era].years}`;$('#dayTag').textContent=`第 ${Math.floor(G.day)} 日`;$('#popGrowthText').textContent=gs==='增长中'?`${gs} ${Math.floor(G.popProgress*100)}% · 约 ${Math.ceil((1-G.popProgress)/Math.max(spd,.0001))} 秒/人`:gs;$('#popGrowthBar').style.width=`${G.popProgress*100}%`;$('#resources').innerHTML=visibleResources().map(k=>`<div class="res"><span>${RES_NAMES[k]}</span><span><b>${fmt(G.resources[k])}</b><span class="rate ${r[k]<0?'neg':''}">${r[k]>=0?'+':''}${fmt(r[k]||0)}/秒</span></span></div>`).join('');let ec=exploreCost();$('#exploreCost').textContent=`探索消耗：${costText(ec)}`;let goal=ERAS[G.era].goal;$('#eraGoal').textContent=G.era===ERAS.length-1?'文明已跨入星际。现在可以追求更高产能并进行传承。':`目标：人口 ${goal.pop} / 知识累计 ${fmt(goal.knowledge)} / 领土 ${goal.territory}`;$('#eraBar').style.width=`${eraProgress()*100}%`;$('#advanceEraBtn').disabled=!canAdvance();$('#advanceEraBtn').textContent=G.era===ERAS.length-1?'已达最高时代':`进入 ${ERAS[G.era+1].name}`;renderJobs();renderBuildings();renderTech();renderBranches();renderTimeline();renderLegacy()}
function renderJobs(){let h='<h2>职业演化</h2><div class="smalltext">每个职业会随时代自动进化，产出与名称同步升级。</div>';for(let[id,j]of Object.entries(JOBS)){if(G.era<j.unlock)continue;let name=j.names[G.era]||j.names[j.names.length-1],next=j.names[Math.min(G.era+1,j.names.length-1)];h+=`<div class="job"><div><div class="jobname">${name}</div><div class="evo">${G.era<10?`下一时代：${next}`:'最终形态'} · 基础产出 ${fmt(jobOutput(id))}/秒</div></div><div class="jobcount">${G.jobs[id]||0}</div><button class="btn" onclick="assignJob('${id}',-1)" ${(G.jobs[id]||0)<=0?'disabled':''}>−</button><button class="btn" onclick="assignJob('${id}',1)" ${idle()<=0?'disabled':''}>＋</button></div>`}$('#tab-jobs').innerHTML=h}
function renderBuildings(){let list=BUILDINGS.filter(b=>b.era<=G.era);$('#tab-buildings').innerHTML='<h2>建造</h2><div class="grid">'+list.map(b=>{let n=bcount(b.id),c=buildingCost(b);return`<div class="card"><div class="row"><h3>${b.name}</h3><span class="badge">×${n}</span></div><div class="desc">${b.desc}</div><div class="cost">${costText(c)}</div><button class="btn" onclick="build('${b.id}')" ${n>=b.max||!canAfford(c)?'disabled':''}>建造</button></div>`}).join('')+'</div>'}
function renderTech(){let list=TECHS.filter(t=>t.era<=G.era&&!G.tech[t.id]);$('#tab-tech').innerHTML='<h2>研究</h2><div class="grid">'+(list.length?list.map(t=>`<div class="card"><h3>${t.name}</h3><div class="desc">${t.desc}</div><div class="cost">${costText(t.cost)}</div><button class="btn" onclick="research('${t.id}')" ${!canAfford(t.cost)?'disabled':''}>研究</button></div>`).join(''):'<div class="desc">当前时代可研究科技已全部完成。</div>')+'</div>'}
function renderBranches(){let h='<h2>发展分支</h2><div class="smalltext">每条路线可随时代继续升级；升级后旧制度会被新制度替代。</div>';for(let group of Object.values(BRANCHES)){h+=`<div class="branch-group"><div class="branch-title">${group.title}</div><div class="grid">`;let chosen=G.branches[group.title];for(let c of group.choices){if(c.era>G.era)continue;h+=`<div class="card ${chosen===c.id?'chosen':''}"><h3>${c.name}</h3><div class="desc">${c.desc}</div><div class="row"><span class="badge">时代 ${ERAS[c.era].name}</span><button class="btn" onclick="chooseBranch('${group.title}','${c.id}')" ${chosen===c.id?'disabled':''}>${chosen===c.id?'当前路线':(chosen?'升级':'选择')}</button></div></div>`}h+='</div></div>'}$('#tab-branches').innerHTML=h}
function renderTimeline(){$('#tab-timeline').innerHTML='<h2>文明纪事</h2>'+TIMELINE.map(m=>`<div class="timeline-item ${G.timeline[m.id]?'done':''}">${G.timeline[m.id]?'[完成]':'[未完成]'} ${m.text}</div>`).join('')}
function renderLegacy(){let bonus=G.legacy*5;$('#tab-legacy').innerHTML=`<h2>传承</h2><div class="desc">抵达星际文明后，可以让本次文明成为传说。祖灵印记永久保留，每个提供 +5% 基础生产加成。</div><div class="res"><span>祖灵印记</span><span>${G.legacy}</span></div><div class="res"><span>永久生产加成</span><span>+${bonus}%</span></div><button class="bigbtn" onclick="prestigeRun()" ${G.era<10?'disabled':''}>让文明成为传说</button>`}
function save(){G.lastSave=Date.now();localStorage.setItem('ember_civilization_v4',JSON.stringify(G))}
function offline(){let elapsed=Math.max(0,(Date.now()-(G.lastSave||Date.now()))/1000);if(elapsed<8)return;let sec=Math.min(elapsed,8*3600),r=rates();for(let k in r){G.resources[k]=Math.max(0,G.resources[k]+r[k]*sec*.6);if(k==='knowledge'&&r[k]>0)G.totalKnowledge+=r[k]*sec*.6}let [s,speed]=growthStatus();if(speed>0){G.popProgress+=speed*sec*.35;let add=Math.min(Math.floor(G.popProgress),Math.max(0,popCap()-G.population));if(add>0){G.population+=add;G.popProgress-=add}}G.seconds+=sec*.6;G.day=1+G.seconds/20;log(`离线 ${Math.floor(elapsed/60)} 分钟，结算了约 ${Math.round(sec*.6)} 秒生产。`,'event')}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));for(let id of ['jobs','buildings','tech','branches','timeline','legacy'])$('#tab-'+id).classList.add('hidden');b.classList.add('active');$('#tab-'+b.dataset.tab).classList.remove('hidden')});
$('#log').innerHTML='';log('三个人围着余火坐下。新的文明从这里开始。','event');offline();render();let last=performance.now(),rt=0,st=0;function loop(now){let dt=Math.min(.5,(now-last)/1000);last=now;tick(dt);rt+=dt;st+=dt;if(rt>.5){render();rt=0}if(st>10){save();st=0}requestAnimationFrame(loop)}requestAnimationFrame(loop);addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});['gesturestart','gesturechange','gestureend'].forEach(t=>document.addEventListener(t,e=>e.preventDefault(),{passive:false}));let lt=0;document.addEventListener('touchend',e=>{let n=Date.now();if(n-lt<320)e.preventDefault();lt=n},{passive:false});